### PR TITLE
Fix stop function

### PR DESCRIPTION
**Pull request by Gabapps**
Hey,
I am currently using your plugin and it looks like there is a mistake in the stop function. You are using the `window.clearInterval()` with your own generated ID.

### CODE REVIEW

**Comment by sdesalas** [comment]
Hi Gabriel, thanks for the fix and for the interest.

I'm pretty sure that `window.clearInterval()` needs an ID passed in rather than a function. When you do `timers[id]` it will pass in a function instead. 

https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/clearInterval

However let me know if you still think I should merge this pull request.

**Comment by sdesalas** [comment]
Looks good thanks for picking that up. Hope you tested this as I haven't had a chance to.

**Comment by Gabapps** [comment]
Yes I tested it in an app. You're welcome, thanks for the plugin ;).

**Comment by Gabapps** [comment]
Hey !

Sorry for the late answer. When you do :

var id = window.setInterval(function(){}, 100);

setInterval returns an ID related to the timer and not a function.

So when you do window.clearInterval(timers[i]), you're passing an ID.

Have a nice day

2016-08-03 9:08 GMT+02:00 Steven de Salas notifications@github.com:

**Comment by sdesalas** [comment]
Yep I saw, well done spotting it.

**Pull request merged**
